name: restrict-pr

on:
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        run: |
          echo "Branch origen: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Solo se permite develop → main"
            exit 1
          fi
